apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: null
  labels:
    app: admin-server
  name: admin-server
spec:
  type: NodePort
  ports:
  - name: http
    port: 9090
    targetPort: 9090
  selector:
    app: admin-server
status:
  loadBalancer: {}
