apiVersion: v1
kind: Service
metadata:
  name: config-server
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.14.0 ()
  creationTimestamp: null
  labels:
    app: config-server
spec:
  ports:
  - name: http
    port: 8888
    targetPort: 8888
  selector:
    app: config-server
status:
  loadBalancer: {}
