apiVersion: v1
kind: Service
metadata:
  name: config-server
  creationTimestamp: null
  labels:
    app: config-server
spec:
  type: NodePort
  ports:
  - name: http
    port: 8888
    targetPort: 8888
  selector:
    app: config-server
status:
  loadBalancer: {}
