apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: null
  labels:
    app: customers-service
  name: customers-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 8081
    targetPort: 8081
  selector:
    app: customers-service
status:
  loadBalancer: {}
