apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: null
  labels:
    app: discovery-server
  name: discovery-server
spec:
  type: NodePort
  ports:
  - name: http
    port: 8761
    targetPort: 8761
  selector:
    app: discovery-server
status:
  loadBalancer: {}
