apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  creationTimestamp: null
  labels:
    app: discovery-server
  name: discovery-server
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: discovery-server
    spec:
      containers:
      - command:
        - java
        - -Djava.security.egd=file:/dev/./urandom
        - -Dspring.cloud.config.uri=http://config-server:8888
        - -jar
        - /app.jar
        image: mszarlinski/spring-petclinic-discovery-server
        name: discovery-server
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8761
        livenessProbe:
          tcpSocket:
            port: 8761
          initialDelaySeconds: 5
          periodSeconds: 20
        readinessProbe:
          tcpSocket:
            port: 8761
          initialDelaySeconds: 5
          periodSeconds: 20
      restartPolicy: Always
status: {}
