apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: null
  labels:
    app: tracing-server
  name: tracing-server
spec:
  type: NodePort
  ports:
  - name: http
    port: 9411
    targetPort: 9411
  selector:
    app: tracing-server
status:
  loadBalancer: {}
