apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  creationTimestamp: null
  labels:
    app: tracing-server
  name: tracing-server
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tracing-server
    spec:
      containers:
      - command:
        - java
        - -Djava.security.egd=file:/dev/./urandom
        - -jar
        - /app.jar
        image: mszarlinski/spring-petclinic-tracing-server
        name: tracing-server
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 9411
        livenessProbe:
          tcpSocket:
            port: 9411
          initialDelaySeconds: 5
          periodSeconds: 20
        readinessProbe:
          tcpSocket:
            port: 9411
          initialDelaySeconds: 5
          periodSeconds: 20
      restartPolicy: Always
status: {}
