apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: null
  labels:
    app: visits-service
  name: visits-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 8082
    targetPort: 8082
  selector:
    app: visits-service
status:
  loadBalancer: {}
