apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  creationTimestamp: null
  labels:
    app: visits-service
  name: visits-service
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: visits-service
    spec:
      containers:
      - command:
        - java
        - -Djava.security.egd=file:/dev/./urandom
        - -Deureka.instance.preferIpAddress=true
        - -jar
        - /app.jar
        image: mszarlinski/spring-petclinic-visits-service
        name: visits-service
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8082
        livenessProbe:
          tcpSocket:
            port: 8082
          initialDelaySeconds: 5
          periodSeconds: 20
        readinessProbe:
          tcpSocket:
            port: 8082
          initialDelaySeconds: 5
          periodSeconds: 20
      restartPolicy: Always
status: {}
